/* Copyright (c) 2011 Danish Maritime Authority.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dk.dma.enav.services.vtsreport.service;



import com.google.common.base.Strings;
import dk.dma.embryo.common.configuration.PropertyFileService;
import dk.dma.embryo.common.mail.MailSender;
import dk.dma.embryo.user.security.Subject;
import dk.dma.enav.services.vtsreport.mail.VtsReportMail;
import lombok.Getter;
import lombok.Setter;

import javax.inject.Inject;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;


/**
 * Created by rob on 5/31/17.
 * <p>
 * Catches JSON from frontend, compiles a nice html email (subject/body) then sends it to the intended address using a backend lookup.
 * TODO - make a service in the maritime cloud which hosts the objects for the VTS interface.
 * TODO - security of the passed strings, injection killing etc.
 */
@SuppressWarnings("all")
@Path("/vtsemail")
public class VtsService {

    @Inject
    private PropertyFileService propertyFileService;

    @Inject
    private MailSender mailSender;

    @Inject
    private Subject subject;

    private String generatedEmailSubject = "";
    private String generatedEmailBody = "";
    private String emailTo = "";
    private String userEmail = "dma.vts.test@gmail.com";


    @GET
    @Produces("text/plain")
    public String getMessage() {
        return "VTS report service endpoint - expecting POST.";
    }

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    public Response createTrackInJSON(Reader vtsdata) {

//        long ts = System.currentTimeMillis();
//        Date localTime = new Date(ts);
        String format = "HH:mm:ss - yyyy/MM/dd";
        SimpleDateFormat sdf = new SimpleDateFormat(format);
        sdf.setTimeZone(TimeZone.getTimeZone("UTC"));
        String UTCtimestamp = sdf.format(new Date());

        //"Example: BELTREP ship report: Brick of the Sea, IMO123456789, 11:15:43 - 2017/05/29 UTC"
        String emailSubject = vtsdata.vtsShortName + " ship report: " + vtsdata.vesselName + ", IMO" + vtsdata.vesselIMO + ", " + UTCtimestamp + " UTC";

        //Start
        String emailBody = "";
        emailBody += "<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional //EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>";
        emailBody += "<html><body style='color: #111111; font-family:Verdana; font-size:11px;'>";

        //General info about this email
        emailBody += "<div style='color:#bbbbbb' font-size:9px;>";
        emailBody += "This email was generated by the Baltic Web interface, as part of the EfficienSea2 project, 2017, by the Danish Maritime Authority, under grant from the European Union's Horizon 2020 research and innovation program, agreement No. 636329.<br>";
        emailBody += "Contact: Department of E-Navigation, sfs@dma.dk<br>";
        emailBody += "Time and date this report was generated:<span style='color:#111111'>" + UTCtimestamp + " UTC</span>";
        emailBody += "</div>";
        emailBody += "<br><br>";

        //VTS report content
        emailBody += "<br><div>";

        if (hasValue(vtsdata.vesselName) || hasValue(vtsdata.vesselCallSign) || hasValue(vtsdata.vesselMMSI)) {
            emailBody += "<span style='text-decoration: underline'>IMO Designator A</span><br>";
        }

        if (hasValue(vtsdata.vesselName)) {
            emailBody += "Vessel name: <strong>" + vtsdata.vesselName + "</strong><br>";
        }
        if (hasValue(vtsdata.vesselCallSign)) {
            emailBody += "Vessel callsign: <strong>" + vtsdata.vesselCallSign + "</strong><br>";
        }
        if (hasValue(vtsdata.vesselMMSI)) {
            emailBody += "Vessel MMSI: <strong>" + vtsdata.vesselMMSI + "</strong><br>";
        }
        emailBody += "<br>";

        if (hasValue(vtsdata.voyageVTSETADateTime)) {
            emailBody += "<span style='text-decoration: underline'>IMO Designator B</span><br>";
            emailBody += "ETA at reporting area: <strong>" + vtsdata.voyageVTSETADateTime + " UTC </strong>";
            emailBody += "<br><br>";
        }

        if (hasValue(vtsdata.voyagePositionLon) && hasValue(vtsdata.voyagePositionLon)) {
            emailBody += "<span style='text-decoration: underline'>IMO Designator C</span><br>";
            emailBody += "Current vessel position: <strong>" + vtsdata.voyagePositionLon + " - " + vtsdata.voyagePositionLat + "</strong>";
            emailBody += "<br><br>";
        }

        if (hasValue(vtsdata.voyageTrueCourse)) {
            emailBody += "<span style='text-decoration: underline'>IMO Designator E</span><br>";
            emailBody += "Vessel true course: <strong>" + vtsdata.voyageTrueCourse + "&deg;</strong>";
            emailBody += "<br><br>";
        }

        if (hasValue(vtsdata.voyageCourseOverGround)) {
            emailBody += "Course Over Ground: <strong>" + vtsdata.voyageCourseOverGround + "&deg;</strong>";
            emailBody += "<br><br>";
        }

        if (hasValue(vtsdata.voyageSpeed)) {
            emailBody += "<span style='text-decoration: underline'>IMO Designator F</span><br>";
            emailBody += "Vessel current speed: <strong>" + vtsdata.voyageSpeed + " knots</strong>";
            emailBody += "<br><br>";
        }

        if (hasValue(vtsdata.voyagePortOfDestination)) {
            emailBody += "<span style='text-decoration: underline'>IMO Designator I</span><br>";
            emailBody += "Destination port: <strong>" + vtsdata.voyagePortOfDestination + "</strong><br>";
            if(hasValue(vtsdata.voyagePortOfDestinationEta)) {
                emailBody += "Expected time of arrival at " + vtsdata.voyagePortOfDestination + ": <strong>" + vtsdata.voyagePortOfDestinationEta + "</strong>";
            }
            emailBody += "<br><br>";
        }

        emailBody += "<span style='text-decoration: underline'>IMO Designator L</span><br>";
        emailBody += "Expected route: <strong>Currently disabled function</strong>";
        emailBody += "<br><br>";

        if (hasValue(vtsdata.vesselDraught)) {
            emailBody += "<span style='text-decoration: underline'>IMO Designator O</span><br>";
            emailBody += "Current maximum draught: <strong>" + vtsdata.vesselDraught + " metres</strong>";
            emailBody += "<br><br>";
        }
        if (hasValue(vtsdata.vesselAirDraught)){
            emailBody += "<span style='text-decoration: underline'>IMO Designator U2</span><br>";
            emailBody += "Current air draught: <strong>" + vtsdata.vesselAirDraught + " metres</strong>";
            emailBody += "<br><br>";
        }

        //Cargo information
        emailBody += "<span style='text-decoration: underline'>IMO Designator P</span><br>";

        if (hasValue(vtsdata.cargoType)) {
            emailBody += "General Cargo Type: <strong>" + vtsdata.cargoType + "</strong><br>";
        }

        if (hasValue(vtsdata.cargoDangerousCargoTotalTonnage)) {
            emailBody += "Total tonnage of dangerous cargo: <strong>" + vtsdata.cargoDangerousCargoTotalTonnage + "</strong><br>"; //always displayed
        }

        if (hasValue(vtsdata.cargoIMOClassesOnBoard)) {
            emailBody += "IMO classes of dangerous cargo: <strong>" + vtsdata.cargoIMOClassesOnBoard + "</strong><br>"; //always displayed
        }

        //Different classes of dangerous cargo
        if (hasValue(vtsdata.cargoIMOClass01)) {
            emailBody += "IMO class 1 cargo tonnage: <strong>" + vtsdata.cargoIMOClass01 + "</strong><br>";
        }
        if (hasValue(vtsdata.cargoIMOClass02)) {
            emailBody += "IMO class 2 cargo tonnage: <strong>" + vtsdata.cargoIMOClass02 + "</strong><br>";
        }
        if (hasValue(vtsdata.cargoIMOClass03)) {
            emailBody += "IMO class 3 cargo tonnage: <strong>" + vtsdata.cargoIMOClass03 + "</strong><br>";
        }
        if (hasValue(vtsdata.cargoIMOClass04)) {
            emailBody += "IMO class 4 cargo tonnage: <strong>" + vtsdata.cargoIMOClass04 + "</strong><br>";
        }
        if (hasValue(vtsdata.cargoIMOClass05)) {
            emailBody += "IMO class 5 cargo tonnage: <strong>" + vtsdata.cargoIMOClass05 + "</strong><br>";
        }
        if (hasValue(vtsdata.cargoIMOClass06)) {
            emailBody += "IMO class 6 cargo tonnage: <strong>" + vtsdata.cargoIMOClass06 + "</strong><br>";
        }
        if (hasValue(vtsdata.cargoIMOClass07)) {
            emailBody += "IMO class 7 cargo tonnage: <strong>" + vtsdata.cargoIMOClass07 + "</strong><br>";
        }
        if (hasValue(vtsdata.cargoIMOClass08)) {
            emailBody += "IMO class 8 cargo tonnage: <strong>" + vtsdata.cargoIMOClass08 + "</strong><br>";
        }
        if (hasValue(vtsdata.cargoIMOClass09)) {
            emailBody += "IMO class 9 cargo tonnage: <strong>" + vtsdata.cargoIMOClass09 + "</strong><br>";
        }
        emailBody += "<br>";

        //vessel defects or deficiencies
        if (hasValue(vtsdata.vesselDefects)) {
            emailBody += "<span style='text-decoration: underline'>IMO Designator Q</span><br>";
            emailBody += "<span style='font-weight: bold; color:#BB0000;'>Vessel defects or deficiencies:</span>";
            emailBody += "<br>" + vtsdata.vesselDefects;
            emailBody += "<br><br>";
        }

        //dangerous cargo or pollutant lost over board
        if (hasValue(vtsdata.cargoPollutantOrDCLostOverBoard)) {
            emailBody += "<span style='text-decoration: underline'>IMO Designator R</span><br>";
            emailBody += "<span style='font-weight: bold; color:#BB0000;'>Dangerous cargo or pollutant lost over board:</span>";
            emailBody += "<br>" + vtsdata.cargoPollutantOrDCLostOverBoard;
            emailBody += "<br><br>";
        }

        if(hasValue(vtsdata.cargoDPAName) || hasValue(vtsdata.cargoDPATelephone) || hasValue(vtsdata.cargoDPAEmail) || hasValue(vtsdata.cargoAdditionalContactInformation)) {
            emailBody += "<span style='text-decoration: underline'>IMO Designator T</span><br>";
            if (hasValue(vtsdata.cargoDPAName)) { //not mandatory
                emailBody += "Name of Designated Person Ashore, or Cargo Agent: <strong>" + vtsdata.cargoDPAName + "</strong><br>";
            }
            if (hasValue(vtsdata.cargoDPATelephone)) { //mandatory
                emailBody += "Telephone: " + vtsdata.cargoDPATelephone + "<br>";
            }
            if (hasValue(vtsdata.cargoDPAEmail)) { //mandatory
                emailBody += "Email: " + vtsdata.cargoDPAEmail + "<br>";
            }
            if (hasValue(vtsdata.cargoAdditionalContactInformation)) { //not mandatory
                emailBody += "Additional contact information for cargo:";
                emailBody += "<br>";
                emailBody += vtsdata.cargoAdditionalContactInformation + "<br>";
            }
            emailBody += "<br>";
        }
        //END cargo information

        if (hasValue(vtsdata.vesselPersonsOnboard)) {
            emailBody += "<span style='text-decoration: underline'>IMO Designator W</span><br>";
            emailBody += "Number of persons on board: <strong>" + vtsdata.vesselPersonsOnboard + "</strong>";
            emailBody += "<br><br>";
        }

        //Bunker information
        boolean fuelHFOHasValue = hasValue(vtsdata.fuelTypeHFORegular) || hasValue(vtsdata.fuelTypeHFOLowSulphur) || hasValue(vtsdata.fuelTypeHFOUltraLowSulphur);
        boolean fuelIFOHasValue = hasValue(vtsdata.fuelTypeIFORegular) || hasValue(vtsdata.fuelTypeIFOLowSulphur) || hasValue(vtsdata.fuelTypeIFOUltraLowSulphur);
        boolean fuelMDOHasValue = hasValue(vtsdata.fuelTypeMDORegular) || hasValue(vtsdata.fuelTypeMDOLowSulphur) || hasValue(vtsdata.fuelTypeMDOUltraLowSulphur);
        boolean fuelMGOHasValue = hasValue(vtsdata.fuelTypeMGORegular) || hasValue(vtsdata.fuelTypeMGOLowSulphur) || hasValue(vtsdata.fuelTypeMGOUltraLowSulphur);

        if (hasValue(vtsdata.fuelTotalFuel) || fuelHFOHasValue || fuelIFOHasValue || fuelMDOHasValue || fuelMGOHasValue || hasValue(vtsdata.fuelTypeLPG) || hasValue(vtsdata.fuelTypeLNG)) {
            emailBody += "<span style='text-decoration: underline'>IMO Designator X</span><br>";

            emailBody += "Total bunker tonnage: <strong>" + vtsdata.fuelTotalFuel + "</strong><br>";

            //HFO
            if (hasValue(vtsdata.fuelTypeHFORegular)) {
                emailBody += "HFO: <strong>" + vtsdata.fuelTypeHFORegular + " tonnes</strong><br>";
            }
            if (hasValue(vtsdata.fuelTypeHFOLowSulphur)) {
                emailBody += "HFO Low Sulphur: <strong>" + vtsdata.fuelTypeHFOLowSulphur + " tonnes</strong><br>";
            }
            if (hasValue(vtsdata.fuelTypeHFOUltraLowSulphur)) {
                emailBody += "HFO Ultra Low Sulphur: <strong>" + vtsdata.fuelTypeHFOUltraLowSulphur + " tonnes</strong><br>";
            }

            //IFO
            if (hasValue(vtsdata.fuelTypeIFORegular)) {
                emailBody += "IFO: <strong>" + vtsdata.fuelTypeIFORegular + " tonnes</strong><br>";
            }
            if (hasValue(vtsdata.fuelTypeIFOLowSulphur)) {
                emailBody += "IFO Low Sulphur: <strong>" + vtsdata.fuelTypeIFOLowSulphur + " tonnes</strong><br>";
            }
            if (hasValue(vtsdata.fuelTypeIFOUltraLowSulphur)) {
                emailBody += "IFO Ultra Low Sulphur: <strong>" + vtsdata.fuelTypeIFOUltraLowSulphur + " tonnes</strong><br>";
            }

            //MDO
            if (hasValue(vtsdata.fuelTypeMDORegular)) {
                emailBody += "MDO: <strong>" + vtsdata.fuelTypeMDORegular + " tonnes</strong><br>";
            }
            if (hasValue(vtsdata.fuelTypeMDOLowSulphur)) {
                emailBody += "MDO Low Sulphur: <strong>" + vtsdata.fuelTypeMDOLowSulphur + " tonnes</strong><br>";
            }
            if (hasValue(vtsdata.fuelTypeMDOUltraLowSulphur)) {
                emailBody += "MDO Ultra Low Sulphur: <strong>" + vtsdata.fuelTypeMDOUltraLowSulphur + " tonnes</strong><br>";
            }

            //MGO
            if (hasValue(vtsdata.fuelTypeMGORegular)) {
                emailBody += "MGO: <strong>" + vtsdata.fuelTypeMGORegular + " tonnes</strong><br>";
            }
            if (hasValue(vtsdata.fuelTypeMGOLowSulphur)) {
                emailBody += "MGO Low Sulphur: <strong>" + vtsdata.fuelTypeMGOLowSulphur + " tonnes</strong><br>";
            }
            if (hasValue(vtsdata.fuelTypeMGOUltraLowSulphur)) {
                emailBody += "MGO Ultra Low Sulphur: <strong>" + vtsdata.fuelTypeMGOUltraLowSulphur + " tonnes</strong><br>";
            }

            //LPG
            if (hasValue(vtsdata.fuelTypeLPG)) {
                emailBody += "LPG: <strong>" + vtsdata.fuelTypeLPG + " tonnes</strong><br>";
            }

            //LPG
            if (hasValue(vtsdata.fuelTypeLNG)) {
                emailBody += "LNG: <strong>" + vtsdata.fuelTypeLNG + " tonnes</strong><br>";
            }
        }
        emailBody += "<br><br>";
        emailBody += "</div>";
        emailBody += "</body></html>";
        //End email


        //for email to actually send
        generatedEmailSubject = emailSubject;
        generatedEmailBody = emailBody;

        //gets the protected email address
        emailTo = propertyFileService.getProperty("vtsservice.emailaddress.by.vtsshortname." + vtsdata.vtsShortName) + ";";

//        userEmail = subject.getUser().getEmail(); //TODO get useremail from whereever it needs to come from

        mailSender.sendEmail(new VtsReportMail(generatedEmailSubject, generatedEmailBody, userEmail, emailTo, propertyFileService));

        //for debug, disable this.
//        return Response.status(201).entity("{\"confirm\":true}").build();

        //For debug, enable this, returns the email header and body with POST status
        return Response.status(201).entity("{\"confirm\":true,\"message\":\""+emailSubject+"<br>"+emailBody+"<br>"+emailTo+"\"}").build();

    }

    private boolean hasValue(String aString) {
        return !Strings.isNullOrEmpty(aString) && !aString.equals("0");
    }

    @Setter
    @Getter
    private static class Reader {
        String vtsShortName;
        String vtsCallSign;
        String vtsEmail;

        String vesselName;
        String vesselCallSign;
        String vesselMMSI;
        String vesselIMO;
        String vesselDraught;
        String vesselAirDraught;
        String vesselPersonsOnboard;
        String vesselLength;
        String vesselDeadWeight;
        String vesselGRT;
        String vesselDefects;
        String vesselType;

        String fuelTotalFuel;
        String fuelTypeHFORegular;
        String fuelTypeHFOLowSulphur;
        String fuelTypeHFOUltraLowSulphur;
        String fuelTypeIFORegular;
        String fuelTypeIFOLowSulphur;
        String fuelTypeIFOUltraLowSulphur;
        String fuelTypeMDORegular;
        String fuelTypeMDOLowSulphur;
        String fuelTypeMDOUltraLowSulphur;
        String fuelTypeMGORegular;
        String fuelTypeMGOLowSulphur;
        String fuelTypeMGOUltraLowSulphur;
        String fuelTypeLPG;
        String fuelTypeLNG;

        String cargoType;
        String cargoIMOClass01;
        String cargoIMOClass02;
        String cargoIMOClass03;
        String cargoIMOClass04;
        String cargoIMOClass05;
        String cargoIMOClass06;
        String cargoIMOClass07;
        String cargoIMOClass08;
        String cargoIMOClass09;
        String cargoDangerousCargoTotalTonnage;
        String cargoDangerousCargoOnBoard;
        String cargoIMOClassesOnBoard;
        String cargoPollutantOrDCLostOverBoard;
        String cargoAdditionalContactInformation;
        String cargoDPAName;
        String cargoDPATelephone;
        String cargoDPAEmail;


        String voyagePositionLon;
        String voyagePositionLat;
        String voyageSpeed;
        String voyageTrueCourse;
        String voyageCourseOverGround;
        String voyagePortOfDestination;
        String voyagePortOfDestinationEta;
        String voyageVTSETADateTime;


    }


}





